/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Cesar Perez
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        optionpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        plantasButton = new javax.swing.JButton();
        ZombiesButton = new javax.swing.JButton();
        atrasButton = new javax.swing.JButton();
        ususarioButton = new javax.swing.JButton();
        dinamicpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Almanaque");
        setLocationByPlatform(true);
        setName("frameAlmanaque"); // NOI18N
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        optionpanel.setBackground(new java.awt.Color(142, 67, 27));

        jLabel1.setBackground(new java.awt.Color(107, 48, 16));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 162, 43));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿QUE DESEA REALIZAR?");

        jLabel2.setBackground(new java.awt.Color(107, 48, 16));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 162, 43));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO AL ALMANAQUE DE PVZ");

        plantasButton.setBackground(new java.awt.Color(86, 33, 7));
        plantasButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        plantasButton.setForeground(new java.awt.Color(221, 162, 43));
        plantasButton.setText("VER PLANTAS");
        plantasButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        plantasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plantasButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        plantasButton.setPreferredSize(new java.awt.Dimension(54, 24));
        plantasButton.setSelected(true);
        plantasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantasButtonActionPerformed(evt);
            }
        });

        ZombiesButton.setBackground(new java.awt.Color(86, 33, 7));
        ZombiesButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        ZombiesButton.setForeground(new java.awt.Color(221, 162, 43));
        ZombiesButton.setText("VER ZOMBIES");
        ZombiesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ZombiesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ZombiesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ZombiesButton.setPreferredSize(new java.awt.Dimension(54, 24));
        ZombiesButton.setSelected(true);
        ZombiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZombiesButtonActionPerformed(evt);
            }
        });

        atrasButton.setBackground(new java.awt.Color(254, 213, 155));
        atrasButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        atrasButton.setForeground(new java.awt.Color(0, 0, 0));
        atrasButton.setText("ATRAS");
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });

        ususarioButton.setBackground(new java.awt.Color(86, 33, 7));
        ususarioButton.setForeground(new java.awt.Color(221, 162, 43));
        ususarioButton.setText("VER USUARIOS");
        ususarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ususarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionpanelLayout = new javax.swing.GroupLayout(optionpanel);
        optionpanel.setLayout(optionpanelLayout);
        optionpanelLayout.setHorizontalGroup(
            optionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionpanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(optionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZombiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(optionpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(optionpanelLayout.createSequentialGroup()
                        .addComponent(atrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ususarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        optionpanelLayout.setVerticalGroup(
            optionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionpanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(plantasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(ZombiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(optionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atrasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ususarioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(optionpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 400));

        dinamicpanel.setBackground(new java.awt.Color(254, 213, 155));

        javax.swing.GroupLayout dinamicpanelLayout = new javax.swing.GroupLayout(dinamicpanel);
        dinamicpanel.setLayout(dinamicpanelLayout);
        dinamicpanelLayout.setHorizontalGroup(
            dinamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        dinamicpanelLayout.setVerticalGroup(
            dinamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        bg.add(dinamicpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plantasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantasButtonActionPerformed
        plantasJPanel plantaP = new plantasJPanel();
        MostrarPanel(plantaP);
    }//GEN-LAST:event_plantasButtonActionPerformed

    private void ZombiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZombiesButtonActionPerformed
        zombiesJPanel zombiP = new zombiesJPanel();
        MostrarPanel(zombiP);
    }//GEN-LAST:event_ZombiesButtonActionPerformed

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        this.setVisible(false);
        FrameLogin lgn = new FrameLogin();
        lgn.setVisible(true);
    }//GEN-LAST:event_atrasButtonActionPerformed

    private void ususarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ususarioButtonActionPerformed
        usuariosJPanel userP = new usuariosJPanel();
        MostrarPanel(userP);
    }//GEN-LAST:event_ususarioButtonActionPerformed

    //------------------------------FUNCIONES-------------------------------------------
        private void MostrarPanel(JPanel p){
        p.setSize(560, 400);
        p.setLocation(0, 0);
        
        
        dinamicpanel.removeAll();
        dinamicpanel.add(p, BorderLayout.CENTER);
        dinamicpanel.revalidate();
        dinamicpanel.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ZombiesButton;
    private javax.swing.JButton atrasButton;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel dinamicpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel optionpanel;
    private javax.swing.JButton plantasButton;
    private javax.swing.JButton ususarioButton;
    // End of variables declaration//GEN-END:variables
}
