/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.ClsConexion;
import Dominio.UsuarioDTO;
import JDBC.UsuarioDAO_JDBC;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar Perez
 */
public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogin
     */
    public FrameLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MensajeTL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userNameTF = new javax.swing.JTextField();
        ingresarButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        userPassTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setLocationByPlatform(true);
        setName("frameLogin"); // NOI18N
        setResizable(false);

        bgLogin.setBackground(new java.awt.Color(94, 97, 128));
        bgLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 165, 44));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO AL LOGIN");
        bgLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 260, 30));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 165, 44));
        jLabel2.setText("USERNAME:");
        bgLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 80, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 165, 44));
        jLabel3.setText("USERPASS:");
        bgLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, 30));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 165, 44));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mensaje:");
        bgLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 80, 30));

        MensajeTL.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        MensajeTL.setForeground(new java.awt.Color(219, 50, 61));
        MensajeTL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bgLogin.add(MensajeTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 610, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bgLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 30));

        userNameTF.setBackground(new java.awt.Color(255, 255, 255));
        userNameTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        userNameTF.setForeground(new java.awt.Color(92, 65, 93));
        userNameTF.setToolTipText("userName");
        bgLogin.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 225, 30));

        ingresarButton.setBackground(new java.awt.Color(36, 34, 57));
        ingresarButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        ingresarButton.setForeground(new java.awt.Color(40, 165, 44));
        ingresarButton.setText("INGRESAR");
        ingresarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarButtonActionPerformed(evt);
            }
        });
        bgLogin.add(ingresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 205, 120, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bgLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 560, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bgLogin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 260, 30));

        userPassTF.setBackground(new java.awt.Color(255, 255, 255));
        userPassTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        userPassTF.setForeground(new java.awt.Color(92, 65, 93));
        userPassTF.setToolTipText("userPass");
        userPassTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        bgLogin.add(userPassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 225, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButtonActionPerformed
        
        UsuarioDTO userLogin = new UsuarioDTO();
        userLogin.setUserName(userNameTF.getText());
        userLogin.setUserPass(userPassTF.getText());
        
        Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            UsuarioDAO_JDBC userJDBC = new UsuarioDAO_JDBC(conn);
            int nValidarUser = 0;
            nValidarUser = userJDBC.selectValidar(userNameTF.getText(), userPassTF.getText());
            if (nValidarUser == 1) {
                this.setVisible(false);
                FrameMain fmain = new FrameMain();
                fmain.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o Clave no validos");
                userNameTF.setText(null);
                userPassTF.setText(null);
            }
            conn.commit();
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            MensajeTL.setText("Error al validar");
        }
        
    }//GEN-LAST:event_ingresarButtonActionPerformed

    //----------------------------FUNCIONES---------------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MensajeTL;
    private javax.swing.JPanel bgLogin;
    private javax.swing.JButton ingresarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JPasswordField userPassTF;
    // End of variables declaration//GEN-END:variables
}
