/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Conexion.ClsConexion;
import Dominio.PlantaDTO;
import JDBC.PlantaDAO_JDBC;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar Perez
 */
public class plantasJPanel extends javax.swing.JPanel {

    /**
     * Creates new form plantasJPanel
     */
    public plantasJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgzombi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mensajeTL = new javax.swing.JLabel();
        idPlantaTF = new javax.swing.JTextField();
        nombrePlantaTF = new javax.swing.JTextField();
        fasePlantaCB = new javax.swing.JComboBox<>();
        buscarPlantaButton = new javax.swing.JButton();
        agregarPlantaButton = new javax.swing.JButton();
        editarPlantaButton = new javax.swing.JButton();
        borrarPlantaButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        limpiarButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipoPlantaTF = new javax.swing.JTextField();
        costePlantaTF = new javax.swing.JTextField();

        bgzombi.setBackground(new java.awt.Color(254, 213, 139));
        bgzombi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(217, 157, 43));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLANTAS");
        bgzombi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 540, 40));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 48, 83));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("FASE:");
        bgzombi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 48, 83));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NOMBRE:");
        bgzombi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 30));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(42, 48, 83));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("COSTE:");
        bgzombi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 70, 30));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(42, 48, 83));
        jLabel5.setText("MENSAJE:");
        bgzombi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 70, 30));

        mensajeTL.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        mensajeTL.setForeground(new java.awt.Color(42, 48, 83));
        mensajeTL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bgzombi.add(mensajeTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 430, 30));

        idPlantaTF.setBackground(new java.awt.Color(255, 255, 255));
        idPlantaTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        idPlantaTF.setForeground(new java.awt.Color(42, 48, 83));
        idPlantaTF.setToolTipText("id de la planta");
        bgzombi.add(idPlantaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 200, 30));

        nombrePlantaTF.setBackground(new java.awt.Color(255, 255, 255));
        nombrePlantaTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        nombrePlantaTF.setForeground(new java.awt.Color(42, 48, 83));
        nombrePlantaTF.setToolTipText("nombre de la planta");
        bgzombi.add(nombrePlantaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 30));

        fasePlantaCB.setBackground(new java.awt.Color(255, 255, 255));
        fasePlantaCB.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        fasePlantaCB.setForeground(new java.awt.Color(42, 48, 83));
        fasePlantaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patio-Dia", "Patio-Noche", "Piscina-Dia", "Piscina-Noche", "Tejado", "Desconocida" }));
        bgzombi.add(fasePlantaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 30));

        buscarPlantaButton.setBackground(new java.awt.Color(235, 185, 126));
        buscarPlantaButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buscarPlantaButton.setForeground(new java.awt.Color(42, 48, 83));
        buscarPlantaButton.setText("BUSCAR");
        buscarPlantaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPlantaButtonActionPerformed(evt);
            }
        });
        bgzombi.add(buscarPlantaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 90, 30));

        agregarPlantaButton.setBackground(new java.awt.Color(235, 185, 126));
        agregarPlantaButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        agregarPlantaButton.setForeground(new java.awt.Color(42, 48, 83));
        agregarPlantaButton.setText("AGREGAR");
        agregarPlantaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPlantaButtonActionPerformed(evt);
            }
        });
        bgzombi.add(agregarPlantaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 245, 90, 30));

        editarPlantaButton.setBackground(new java.awt.Color(235, 185, 126));
        editarPlantaButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        editarPlantaButton.setForeground(new java.awt.Color(42, 48, 83));
        editarPlantaButton.setText("EDITAR");
        editarPlantaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPlantaButtonActionPerformed(evt);
            }
        });
        bgzombi.add(editarPlantaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 245, 90, 30));

        borrarPlantaButton.setBackground(new java.awt.Color(235, 185, 126));
        borrarPlantaButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        borrarPlantaButton.setForeground(new java.awt.Color(42, 48, 83));
        borrarPlantaButton.setText("BORRAR");
        borrarPlantaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPlantaButtonActionPerformed(evt);
            }
        });
        bgzombi.add(borrarPlantaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 245, 90, 30));
        bgzombi.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 360, 20));

        limpiarButton.setBackground(new java.awt.Color(235, 185, 126));
        limpiarButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        limpiarButton.setForeground(new java.awt.Color(42, 48, 83));
        limpiarButton.setText("LIMPIAR");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        bgzombi.add(limpiarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 90, 30));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(42, 48, 83));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ID:");
        bgzombi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 70, 30));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(42, 48, 83));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("TIPO:");
        bgzombi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, 30));

        tipoPlantaTF.setBackground(new java.awt.Color(255, 255, 255));
        tipoPlantaTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        tipoPlantaTF.setForeground(new java.awt.Color(42, 48, 83));
        tipoPlantaTF.setToolTipText("tipo de planta");
        bgzombi.add(tipoPlantaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 200, 30));

        costePlantaTF.setBackground(new java.awt.Color(255, 255, 255));
        costePlantaTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        costePlantaTF.setForeground(new java.awt.Color(42, 48, 83));
        costePlantaTF.setToolTipText("coste de la planta");
        costePlantaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costePlantaTFKeyTyped(evt);
            }
        });
        bgzombi.add(costePlantaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgzombi, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgzombi, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarPlantaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPlantaButtonActionPerformed
               Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            PlantaDAO_JDBC pjdbc = new PlantaDAO_JDBC(conn);
            PlantaDTO buscarPlanta = new PlantaDTO();
            buscarPlanta = pjdbc.select(Integer.parseInt(idPlantaTF.getText()));

            nombrePlantaTF.setText(buscarPlanta.getNombre_planta());
            tipoPlantaTF.setText(buscarPlanta.getTipo_planta());
            for (int i = 0; i < 5; i++) {
                if (buscarPlanta.getFase_desbloqueoPlanta().equalsIgnoreCase(fasePlantaCB.getSelectedItem().toString())) {
                    costePlantaTF.setText(String.valueOf(buscarPlanta.getCoste_solesPlanta()));
                    conn.commit();
                    mensajeTL.setText("Commit realizado, planta buscada");
                    break;
                }
                else{
                    fasePlantaCB.setSelectedIndex(i);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            mensajeTL.setText("Error al buscar, entramos al rollback");
            try {
                conn.rollback();
            } catch (SQLException ex1) {
                mensajeTL.setText("Error SQL: "+ex1.getMessage());
                ex1.printStackTrace(System.out);
            }
        }
    }//GEN-LAST:event_buscarPlantaButtonActionPerformed

    private void agregarPlantaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPlantaButtonActionPerformed

        Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            PlantaDAO_JDBC pjdbc = new PlantaDAO_JDBC(conn);
            PlantaDTO agregarPlanta = new PlantaDTO();

            agregarPlanta.setNombre_planta(nombrePlantaTF.getText());
            agregarPlanta.setTipo_planta(tipoPlantaTF.getText());
            agregarPlanta.setFase_desbloqueoPlanta(fasePlantaCB.getSelectedItem().toString());
            agregarPlanta.setCoste_solesPlanta(Integer.parseInt(costePlantaTF.getText()));

            pjdbc.insert(agregarPlanta);
            conn.commit();
            mensajeTL.setText("Commit realizado, planta ingresada");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            mensajeTL.setText("Error al insertar, entramos al rollback");
            try {
                conn.rollback();
            } catch (SQLException ex1) {
                mensajeTL.setText("Error SQL: "+ex1.getMessage());
                ex1.printStackTrace(System.out);
            }
        }
        
    }//GEN-LAST:event_agregarPlantaButtonActionPerformed

    private void editarPlantaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPlantaButtonActionPerformed
        
        Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            PlantaDAO_JDBC pjdbc = new PlantaDAO_JDBC(conn);
            PlantaDTO editarPlanta = new PlantaDTO();

            editarPlanta.setId_planta(Integer.parseInt(idPlantaTF.getText()));
            editarPlanta.setNombre_planta(nombrePlantaTF.getText());
            editarPlanta.setTipo_planta(tipoPlantaTF.getText());
            editarPlanta.setFase_desbloqueoPlanta(fasePlantaCB.getSelectedItem().toString());
            editarPlanta.setCoste_solesPlanta(Integer.parseInt(costePlantaTF.getText()));
            pjdbc.update(editarPlanta);
            conn.commit();
            mensajeTL.setText("Commit realizado, planta actualizada");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            mensajeTL.setText("Error al actualizar, entramos al rollback");
            try {
                conn.rollback();
            } catch (SQLException ex1) {
                mensajeTL.setText("Error SQL: "+ex1.getMessage());
                ex1.printStackTrace(System.out);
            }
        }
        
    }//GEN-LAST:event_editarPlantaButtonActionPerformed

    private void borrarPlantaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPlantaButtonActionPerformed

        Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            PlantaDAO_JDBC pjdbc = new PlantaDAO_JDBC(conn);
            PlantaDTO borrarPlanta = new PlantaDTO();

            borrarPlanta.setId_planta(Integer.parseInt(idPlantaTF.getText()));
            borrarPlanta.setNombre_planta(nombrePlantaTF.getText());
            borrarPlanta.setTipo_planta(nombrePlantaTF.getText());
            borrarPlanta.setFase_desbloqueoPlanta(fasePlantaCB.getSelectedItem().toString());
            borrarPlanta.setCoste_solesPlanta(Integer.parseInt(costePlantaTF.getText()));
            pjdbc.delete(borrarPlanta);
            conn.commit();
            mensajeTL.setText("Commit realizado, planta eliminada");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            mensajeTL.setText("Error al eliminar, entramos al rollback");
            try {
                conn.rollback();
            } catch (SQLException ex1) {
                mensajeTL.setText("Error SQL: "+ex1.getMessage());
                ex1.printStackTrace(System.out);
            }
        }
        
    }//GEN-LAST:event_borrarPlantaButtonActionPerformed

    //----------------------------------------FUNCIONES---------------------------------------------

    
    
    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        idPlantaTF.setText(null);
        nombrePlantaTF.setText(null);
        tipoPlantaTF.setText(null);
        fasePlantaCB.setSelectedIndex(0);
        costePlantaTF.setText(null);
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void costePlantaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costePlantaTFKeyTyped
        char c = evt.getKeyChar();
        
        if ((c < '0') || (c > '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingresar números");
        }
    }//GEN-LAST:event_costePlantaTFKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPlantaButton;
    private javax.swing.JPanel bgzombi;
    private javax.swing.JButton borrarPlantaButton;
    private javax.swing.JButton buscarPlantaButton;
    private javax.swing.JTextField costePlantaTF;
    private javax.swing.JButton editarPlantaButton;
    private javax.swing.JComboBox<String> fasePlantaCB;
    private javax.swing.JTextField idPlantaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JLabel mensajeTL;
    private javax.swing.JTextField nombrePlantaTF;
    private javax.swing.JTextField tipoPlantaTF;
    // End of variables declaration//GEN-END:variables
}
