/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Conexion.ClsConexion;
import Dominio.UsuarioDTO;
import JDBC.UsuarioDAO_JDBC;
import java.sql.*;

/**
 *
 * @author Cesar Perez
 */
public class usuariosJPanel extends javax.swing.JPanel {

    /**
     * Creates new form usuariosJPanel
     */
    public usuariosJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bguser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mensajeTL = new javax.swing.JLabel();
        idUserTF = new javax.swing.JTextField();
        userPassTF = new javax.swing.JTextField();
        buscarUserButton = new javax.swing.JButton();
        agregarUserButton = new javax.swing.JButton();
        editarUserButton = new javax.swing.JButton();
        borrarUserButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        limpiarButton = new javax.swing.JButton();
        userNameTF = new javax.swing.JTextField();

        bguser.setBackground(new java.awt.Color(254, 213, 139));
        bguser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(217, 157, 43));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIOS");
        bguser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 540, 40));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 48, 83));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID:");
        bguser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 48, 83));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NOMBRE:");
        bguser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, 30));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(42, 48, 83));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CLAVE:");
        bguser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 30));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(42, 48, 83));
        jLabel5.setText("MENSAJE:");
        bguser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 70, 30));

        mensajeTL.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        mensajeTL.setForeground(new java.awt.Color(42, 48, 83));
        mensajeTL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bguser.add(mensajeTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 430, 30));

        idUserTF.setBackground(new java.awt.Color(255, 255, 255));
        idUserTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        idUserTF.setForeground(new java.awt.Color(42, 48, 83));
        idUserTF.setToolTipText("id Usuario");
        bguser.add(idUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, 30));

        userPassTF.setBackground(new java.awt.Color(255, 255, 255));
        userPassTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        userPassTF.setForeground(new java.awt.Color(42, 48, 83));
        userPassTF.setToolTipText("Clave del usuario");
        bguser.add(userPassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, 30));

        buscarUserButton.setBackground(new java.awt.Color(235, 185, 126));
        buscarUserButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buscarUserButton.setForeground(new java.awt.Color(42, 48, 83));
        buscarUserButton.setText("BUSCAR");
        buscarUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUserButtonActionPerformed(evt);
            }
        });
        bguser.add(buscarUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 90, 30));

        agregarUserButton.setBackground(new java.awt.Color(235, 185, 126));
        agregarUserButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        agregarUserButton.setForeground(new java.awt.Color(42, 48, 83));
        agregarUserButton.setText("AGREGAR");
        agregarUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUserButtonActionPerformed(evt);
            }
        });
        bguser.add(agregarUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 30));

        editarUserButton.setBackground(new java.awt.Color(235, 185, 126));
        editarUserButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        editarUserButton.setForeground(new java.awt.Color(42, 48, 83));
        editarUserButton.setText("EDITAR");
        editarUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUserButtonActionPerformed(evt);
            }
        });
        bguser.add(editarUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 90, 30));

        borrarUserButton.setBackground(new java.awt.Color(235, 185, 126));
        borrarUserButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        borrarUserButton.setForeground(new java.awt.Color(42, 48, 83));
        borrarUserButton.setText("BORRAR");
        borrarUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarUserButtonActionPerformed(evt);
            }
        });
        bguser.add(borrarUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 90, 30));
        bguser.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 360, 20));

        limpiarButton.setBackground(new java.awt.Color(235, 185, 126));
        limpiarButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        limpiarButton.setForeground(new java.awt.Color(42, 48, 83));
        limpiarButton.setText("LIMPIAR");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        bguser.add(limpiarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 90, 30));

        userNameTF.setBackground(new java.awt.Color(255, 255, 255));
        userNameTF.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        userNameTF.setForeground(new java.awt.Color(42, 48, 83));
        userNameTF.setToolTipText("userName");
        bguser.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bguser, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bguser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUserButtonActionPerformed

                Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            UsuarioDAO_JDBC ujdbc = new UsuarioDAO_JDBC(conn);
            UsuarioDTO buscarUser = new UsuarioDTO();
            buscarUser = ujdbc.select(Integer.parseInt(idUserTF.getText()));

            userNameTF.setText(buscarUser.getUserName());
            userPassTF.setText(buscarUser.getUserPass());
            mensajeTL.setText("Listo, usuario encontrado");
            conn.commit();
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            mensajeTL.setText("Error al buscar, entramos al rollback");
            try {
                conn.rollback();
            } catch (SQLException ex1) {
                mensajeTL.setText("Error SQL: "+ex1.getMessage());
                ex1.printStackTrace(System.out);
            }
        }
        
    }//GEN-LAST:event_buscarUserButtonActionPerformed

    private void agregarUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUserButtonActionPerformed

                Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            UsuarioDAO_JDBC ujdbc = new UsuarioDAO_JDBC(conn);
            UsuarioDTO agregarUser = new UsuarioDTO();

            agregarUser.setUserName(userNameTF.getText());
            agregarUser.setUserPass(userPassTF.getText());
            ujdbc.insert(agregarUser);
            conn.commit();
            mensajeTL.setText("Commit realizado, Usuario ingresado");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            mensajeTL.setText("Error al insertar, entramos al rollback");
            try {
                conn.rollback();
            } catch (SQLException ex1) {
                mensajeTL.setText("Error SQL: "+ex1.getMessage());
                ex1.printStackTrace(System.out);
            }
        }
        
    }//GEN-LAST:event_agregarUserButtonActionPerformed

    private void editarUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUserButtonActionPerformed
        
        Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            UsuarioDAO_JDBC ujdbc = new UsuarioDAO_JDBC(conn);
            UsuarioDTO editarUser = new UsuarioDTO();

            editarUser.setIdUsuario(Integer.parseInt(idUserTF.getText()));
            editarUser.setUserName(userNameTF.getText());
            editarUser.setUserPass(userPassTF.getText());
            ujdbc.update(editarUser);
            conn.commit();
            mensajeTL.setText("Commit realizado, Usuario actualizado");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            mensajeTL.setText("Error al actualizar, entramos al rollback");
            try {
                conn.rollback();
            } catch (SQLException ex1) {
                mensajeTL.setText("Error SQL: "+ex1.getMessage());
                ex1.printStackTrace(System.out);
            }
        }
        
    }//GEN-LAST:event_editarUserButtonActionPerformed

    private void borrarUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarUserButtonActionPerformed
        
        Connection conn = null;
        try {
            conn = ClsConexion.getConnection();
            if (conn.getAutoCommit()) {
                conn.setAutoCommit(false);
            }

            UsuarioDAO_JDBC ujdbc = new UsuarioDAO_JDBC(conn);
            UsuarioDTO borrarUser = new UsuarioDTO();

            borrarUser.setIdUsuario(Integer.parseInt(idUserTF.getText()));
            borrarUser.setUserName(userNameTF.getText());
            borrarUser.setUserPass(userPassTF.getText());
            ujdbc.delete(borrarUser);
            conn.commit();
            mensajeTL.setText("Commit realizado, Usuario eliminado");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            mensajeTL.setText("Error al eliminar, entramos al rollback");
            try {
                conn.rollback();
            } catch (SQLException ex1) {
                mensajeTL.setText("Error SQL: "+ex1.getMessage());
                ex1.printStackTrace(System.out);
            }
        }
        
    }//GEN-LAST:event_borrarUserButtonActionPerformed

    //-----------------------------FUNCIONES------------------------------------

    
    
    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        idUserTF.setText(null);
        userNameTF.setText(null);
        userPassTF.setText(null);
    }//GEN-LAST:event_limpiarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarUserButton;
    private javax.swing.JPanel bguser;
    private javax.swing.JButton borrarUserButton;
    private javax.swing.JButton buscarUserButton;
    private javax.swing.JButton editarUserButton;
    private javax.swing.JTextField idUserTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JLabel mensajeTL;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JTextField userPassTF;
    // End of variables declaration//GEN-END:variables
}
